version: '3.5'
services:
    feishin:
        container_name: feishin
        image: feishin
        restart: unless-stopped
        ports:
            - 9180:9180
        environment:
            - SERVER_NAME=jellyfin # pre defined server name
            - SERVER_LOCK=true # When true only username and password fields will be enabled
            - SERVER_TYPE=navidrome #NAVIDROME also works
            - SERVER_URL= #http://address:port

